### ISSUE TITLE
'extra_fields' error

### ISSUE THREAD

**Issue by kdemuren** [ParkerLab/atactk#1]
Hi,

When I run the make_cut_matrix program, I get an error that reads:

2016-08-01 13:47:14,478 ERROR 'extra_fields'
Traceback (most recent call last):
  File "/net/bmc-pub7/data2/boyerlab/users/kdemuren/lib/python2.7/site-packages/atactk-0.1.5-py2.7.egg/EGG-INFO/scripts/make_cut_matrix", line 235, in make_cut_matrix
    for motif_count, (motif, row, tree) in enumerate(results, 1):
  File "/net/bmc-pub7/data2/boyerlab/users/kdemuren/lib/python2.7/site-packages/atactk-0.1.5-py2.7.egg/EGG-INFO/scripts/make_cut_matrix", line 232, in <genexpr>
    results = (score(motif) for motif in motifs)
  File "/home/kdemuren/lib/python2.7/site-packages/atactk-0.1.5-py2.7.egg/atactk/data.py", line 212, in read_features
    del row['extra_fields']
KeyError: 'extra_fields'

My command syntax was:

make_cut_matrix -d -b '(36-149 150-324 325-400 1)' CM_ATAC_rep1_1_1.bam MA0052_matches.bed.gz | gzip -c > MEF2A.discrete.matrix.gz

Any suggestions on how to fix this?

Thanks for your time,
Kunle

**Comment by umijh** [comment]
Thanks Kunle, and sorry about the bug. This should be fixed in 0.1.6 (60b321a). If you update your clone of the repo with `git pull` and run `pip install /path/to/clone` again, your command above should work. If it doesn't, please let me know.

**Comment by umijh** [comment]
Actually, 0.1.6 is revision 6cd7de0.

**Comment by kdemuren** [comment]
Thanks, seems to have worked fine!
