### ISSUE TITLE
make cut matrix AttributeError: 'Symbol' object has no attribute 'value'

### ISSUE THREAD

**Issue by Zhiyi-Chen17** [ParkerLab/atactk#6]
Hi, rdalbanus，thanks for providing such a good tool.

(cutruntools2.1) chenzhiyi@luo-lab-tower:~/Software/CUT-RUNTools-2.0-master/install$ /home/chenzhiyi/.local/bin/make_cut_matrix -v -b '(25-150 1)' -d -o 0 -r 100 -p 1 -f 3 -F 4 -F 8 -q 0 /media/dell/data2/chenzhiyi/bulk-example-test/PRDM9/aligned/dedup.120bp/PRDM9.bam fimo.bed > fimo.cuts.freq.txt
Traceback (most recent call last):
  File "/home/chenzhiyi/.local/bin/make_cut_matrix", line 277, in <module>
    make_cut_matrix(parse_arguments())
  File "/home/chenzhiyi/.local/bin/make_cut_matrix", line 182, in parse_arguments
    return parser.parse_args()
  File "/home/chenzhiyi/miniconda3/envs/cutruntools2.1/lib/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/chenzhiyi/miniconda3/envs/cutruntools2.1/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/chenzhiyi/miniconda3/envs/cutruntools2.1/lib/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/chenzhiyi/miniconda3/envs/cutruntools2.1/lib/python3.6/argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "/home/chenzhiyi/miniconda3/envs/cutruntools2.1/lib/python3.6/argparse.py", line 1824, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/home/chenzhiyi/miniconda3/envs/cutruntools2.1/lib/python3.6/argparse.py", line 2265, in _get_values
    value = self._get_value(action, arg_string)
  File "/home/chenzhiyi/miniconda3/envs/cutruntools2.1/lib/python3.6/argparse.py", line 2294, in _get_value
    result = type_func(arg_string)
  File "/home/chenzhiyi/.local/lib/python3.6/site-packages/atactk/command.py", line 126, in parse_bins
    bin_string = bin_string.value()
AttributeError: 'Symbol' object has no attribute 'value'

**Comment by rdalbanus** [comment]
Hi @zyyyyy11144, thank you so much for using our tool! There might be something off with the invocation based on the errors thrown, but I cannot find anything explicitly wrong in your command. 

Can you run the [examples from the documentation](https://atactk.readthedocs.io/en/latest/usage.html#cut-matrix-generation) in your data without any errors? E.g. `make_cut_matrix -d -b '(36-149 150-324 325-400 1)' input.bam motif.bed`. 

If so, then one of your flags is causing the issue - I'd try adding them one by one to the example to see where it breaks.


If not, then it might be something with your input data. In that case:
1) Can you post the first 5 lines of the motif bed file? 
2) What is the total number of lines in the motif bed file?
3) Is your bed file tab-separated? This may seem like a dumb question, but sometimes, the tabs are converted to spaces depending on how you process your files.
